//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMHelper.BoardParsing.OpenCV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMHelper.BoardParsing.OpenCV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_2_1 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_2_2 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_2_3 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_2_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_2_4 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_2_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_3_1 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_3_2 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_3_3 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_3_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_3_4 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_3_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_3_5 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_3_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_3_6 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_3_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_5_1 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_5_2 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_5_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_5_3 {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_5_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_Blue {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_Green {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_Green", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_Red {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_Red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Autumn_Battle_Skull {
            get {
                object obj = ResourceManager.GetObject("Autumn_Battle_Skull", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_2_1 {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_2_2 {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_2_3 {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_2_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_3_1 {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_3_2 {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_3_3 {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_3_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_Blue {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_Green {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_Green", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_Maroon {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_Maroon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_Purple {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_Purple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_Red {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_Red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Classic_BoxOfSages_Yellow {
            get {
                object obj = ResourceManager.GetObject("Classic_BoxOfSages_Yellow", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
